### ISSUE TITLE
Marcadores en mapa : 5

### ISSUE THREAD

**Issue by zaragozamartin91** [zaragozamartin91/TDP2-G5-2019-2C-Android#6]
Depende de #1 , #2 , #7 

Agregar un boton flotante a la pantalla de mapa (un Floating Action Button / FAB). Al presionar este boton, se debe obtener la ubicacion actual del usuario, los ATMs a partir de los filtros establecidos (si los filtros aun no fueron colocados, entonces probar con filtros o datos de atm "de juguete"). 

Si no es posible obtener la ubicacion actual , mostrar un mensaje "se necesita geolocalizacion para continuar"

Si no se obtienen resultados, mostrar un mensaje (usando un Toast, por ejemplo) informando "que no existen resultados para el radio buscado y que intente con un radio más grande".

Si no existen resultados para la búsqueda y está seleccionado el radio más grande deberá
informar (mediante un Toast por ejemplo) "que no existen resultados para la búsqueda y que se mueva por la ciudad antes de volver a buscar"

Si se obtienen resultados se deben agregar marcadores al mapa a partir de los datos de latitud y longitud.

Cada marcador sobre el mapa debe mostrar los siguientes datos:
* Dirección
* Banco
* Red
* Cantidad de terminales

**Comment by nanigalli** [comment]
Los mensajes aprobados relacionados con este ticket son los siguientes:

3- Si no se puede obtener la ubicación, se mostrará un mensaje indicando la necesidad de geolocalizar para continuar.

**Mensaje** : _"No se puede obtener la ubicación. Por favor active la ubicación y vuelva a intentarlo"_

4- Si no existen resultados para la búsqueda deberá informar que no existen resultados para el radio buscado y que intente con un radio más grande.

**Mensaje** : _"No existen resultados. Por favor pruebe con un radio más grande"_

5- Si no existen resultados para la búsqueda y está seleccionado el radio más grande deberá informar que no existen resultados para la búsqueda y que se mueva por la ciudad antes de volver a buscar.

**Mensaje** : _"No existen resultados. Por favor muevase por la ciudad y vuelva a intentarlo"_

6- Si el usuario rechaza dar los permisos para ver la ubicacion de su celular, entonces se va a mostrar el siguiente mensaje:

**Mensaje** : _"Se necesita el permiso para ver la ubicacion del dispositivo antes de seguir"_
