### ISSUE TITLE
Conectividad : 3

### ISSUE THREAD

**Issue by zaragozamartin91** [zaragozamartin91/TDP2-G5-2019-2C-Android#8]
Configurar la app (mediante los archivos de configuracion del Manifest de android o algo asi) para que la misma cuente con permisos de red (o salida a internet).

Al iniciar la app si no se cuenta con permisos de red, mostrar una ventana con el mensaje "se necesita conectividad para seguir operando". Al cerrar la ventana se debe cerrar la app.

Agregar chequeo de conectividad periodico (mediante un thread o algun mecanismo estandar de Android). En caso de detectar perdida de conexion, mostrar un mensaje (como un toast) "se perdio conectividad"

**Comment by nanigalli** [comment]
Mensajes que tenemos que devolverle al usuario relacionado con este ticket:

1- Si ingreso y no hay conectividad, muestra un mensaje indicando que se necesita conectividad
y sino no permite continuar operando

**Mensaje**: _"No tienes conexión a Internet. Por favor active el Wifi o los datos moviles y vuelva a intentarlo"_

2- Si estoy dentro de la aplicación y se pierde la conectividad aparecerá un mensaje indicando el
problema pero no bloqueará el uso

**Mensaje**: _"Se perdió la conexión a Internet. Por favor active el Wifi o los datos moviles y vuelva a intentarlo"_
